SELECT 
    C1.CAR_ID, 
    C1.CAR_TYPE, 
    ROUND((C1.DAILY_FEE * (100-C3.DISCOUNT_RATE) / 100 * 30)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C1
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C3
ON C1.CAR_TYPE = C3.CAR_TYPE
WHERE C1.CAR_TYPE IN ('세단', 'SUV') AND 
        C3.DURATION_TYPE = '30일 이상'AND
        NOT EXISTS(
        SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C3
    WHERE C1.CAR_ID = C3.CAR_ID AND
    C3.START_DATE <= '2022-11-30'AND 
      C3.END_DATE >= '2022-11-01'
)
GROUP BY C1.CAR_ID, C1.CAR_TYPE
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;