SELECT U2.USER_ID,U2.NICKNAME,
CONCAT(U2.CITY, ' ', U2.STREET_ADDRESS1, ' ', U2.STREET_ADDRESS2) AS '전체주소',
CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-',SUBSTRING(TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_BOARD U1
JOIN USED_GOODS_USER U2
ON U1.WRITER_ID = U2.USER_ID
GROUP BY USER_ID
HAVING COUNT(*) >= 3
ORDER BY U2.USER_ID DESC;