-- 1. 0부터 23까지의 숫자를 가지는 재귀 테이블(WITH RECURSIVE) 생성
WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME_TABLE WHERE HOUR < 23
)

-- 2. 생성한 시간 테이블에 실제 데이터 LEFT JOIN
SELECT 
    T.HOUR, 
    COUNT(A.ANIMAL_ID) AS COUNT -- COUNT(*)가 아닌 특정 컬럼을 세어야 null이 0으로 집계됨
FROM TIME_TABLE T
LEFT JOIN ANIMAL_OUTS A 
    ON T.HOUR = HOUR(A.DATETIME)
GROUP BY T.HOUR
ORDER BY T.HOUR ASC;